/**
 * Rule catalog.
 *
 * Rule identifiers are a public contract: they appear in reports, in CI
 * failure conditions, and in user configuration. An identifier's meaning must
 * never change silently (see docs/RELEASE.md § Rule stability).
 *
 * A catalog entry declares intent and ownership; the executable rule lives in
 * the package named by `implementedIn`. `status` states honestly whether the
 * rule is implemented in this build.
 */

import type { Severity } from '../severity.js';

export const RULE_CATEGORIES = [
  'PERFORMANCE',
  'DEPENDENCIES',
  'SECURITY',
  'INTEGRITY',
  'CONFIGURATION',
  'ERRORS',
] as const;

export type RuleCategory = (typeof RULE_CATEGORIES)[number];

export type RuleStatus = 'IMPLEMENTED' | 'NOT_IMPLEMENTED';

/** Development gate that owns delivery of a rule (see docs/GATE_STATUS.md). */
export type GateNumber = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

export interface RuleCatalogEntry {
  readonly id: string;
  readonly category: RuleCategory;
  /** Severity the rule emits by default; individual findings may lower it with reason. */
  readonly defaultSeverity: Severity;
  readonly title: string;
  /** What the rule looks for. */
  readonly description: string;
  /** Why the finding matters to a server operator. */
  readonly rationale: string;
  /** Known conditions under which this rule can report a benign pattern. */
  readonly falsePositives: readonly string[];
  /** Evidence the rule must attach before emitting a finding. */
  readonly evidenceRequirements: readonly string[];
  readonly status: RuleStatus;
  readonly targetGate: GateNumber;
  /** Workspace package that implements (or will implement) the rule. */
  readonly implementedIn: string;
}

const ENTRIES: readonly RuleCatalogEntry[] = Object.freeze([
  {
    id: 'CFG-MANIFEST-001',
    category: 'CONFIGURATION',
    defaultSeverity: 'MEDIUM',
    title: 'Malformed or incomplete resource manifest',
    description:
      'Detects fxmanifest.lua / __resource.lua files that cannot be parsed, or that omit declarations required for the resource to load predictably.',
    rationale:
      'A manifest that cannot be parsed by the server prevents the resource from starting, or starts it with silently missing scripts.',
    falsePositives: [
      'Manifests using vendor-specific directives that are valid at runtime but unknown to the parser.',
      'Conditional manifest structures generated by build tooling.',
    ],
    evidenceRequirements: ['FILE_REFERENCE pointing at the manifest', 'CODE_PATTERN or CONFIG_VALUE for the offending declaration'],
    status: 'NOT_IMPLEMENTED',
    targetGate: 1,
    implementedIn: '@sentinel-forge/scanner',
  },
  {
    id: 'CFG-MISSING-FILE-001',
    category: 'CONFIGURATION',
    defaultSeverity: 'HIGH',
    title: 'Manifest references a file that does not exist',
    description:
      'Detects script/file globs declared in a manifest that resolve to no file on disk.',
    rationale:
      'The referenced script never loads, which usually surfaces later as an unexplained runtime error rather than a startup failure.',
    falsePositives: [
      'Files generated at build time and absent from a source checkout.',
      'Glob patterns intentionally matching an optional file set.',
    ],
    evidenceRequirements: ['FILE_REFERENCE with the manifest line', 'CONFIG_VALUE containing the unresolved reference'],
    status: 'NOT_IMPLEMENTED',
    targetGate: 1,
    implementedIn: '@sentinel-forge/scanner',
  },
  {
    id: 'DEP-MISSING-001',
    category: 'DEPENDENCIES',
    defaultSeverity: 'HIGH',
    title: 'Declared dependency was not found',
    description:
      'Detects a resource whose manifest declares a dependency that is not present in the scanned server.',
    rationale:
      'A missing dependency typically prevents the dependent resource from functioning, often without a clear error message.',
    falsePositives: [
      'Dependencies provided by the server artifact rather than the resources directory.',
      'Optional dependencies declared as hard dependencies by the resource author.',
    ],
    evidenceRequirements: ['FILE_REFERENCE with the dependency declaration', 'RELATIONSHIP describing the unresolved edge'],
    status: 'NOT_IMPLEMENTED',
    targetGate: 1,
    implementedIn: '@sentinel-forge/dependencies',
  },
  {
    id: 'DEP-CYCLE-001',
    category: 'DEPENDENCIES',
    defaultSeverity: 'MEDIUM',
    title: 'Dependency cycle detected',
    description: 'Detects a cycle in the resource dependency graph.',
    rationale:
      'Cycles make load order non-deterministic and can produce intermittent startup failures that are hard to reproduce.',
    falsePositives: [
      'Mutually optional resources that tolerate either load order at runtime.',
    ],
    evidenceRequirements: ['RELATIONSHIP for each edge in the cycle'],
    status: 'NOT_IMPLEMENTED',
    targetGate: 1,
    implementedIn: '@sentinel-forge/dependencies',
  },
  {
    id: 'PERF-LOOP-001',
    category: 'PERFORMANCE',
    defaultSeverity: 'MEDIUM',
    title: 'Loop without an observable yield',
    description:
      'Detects a continuous loop construct whose analyzed body contains no Wait/Citizen.Wait or other yielding call.',
    rationale:
      'A thread that never yields blocks the runtime scheduler and is a common source of server-wide hitching.',
    falsePositives: [
      'Loops that yield through a helper function the static analyzer cannot follow.',
      'Loops that terminate quickly on a bounded collection.',
      'Wait(0) is a legitimate pattern in per-frame code and is not by itself a defect.',
    ],
    evidenceRequirements: ['FILE_REFERENCE with the loop line', 'CODE_PATTERN containing the loop construct'],
    status: 'NOT_IMPLEMENTED',
    targetGate: 2,
    implementedIn: '@sentinel-forge/analyzer',
  },
  {
    id: 'PERF-EVENT-001',
    category: 'PERFORMANCE',
    defaultSeverity: 'MEDIUM',
    title: 'Event trigger in a hot path',
    description:
      'Detects network event triggers issued from inside a loop or per-frame thread.',
    rationale:
      'High-frequency event traffic consumes bandwidth and server CPU disproportionately to the work performed.',
    falsePositives: [
      'Triggers guarded by a state check that only fires rarely at runtime.',
      'Loops with a long wait interval.',
    ],
    evidenceRequirements: ['FILE_REFERENCE with the trigger line', 'CODE_PATTERN for the enclosing loop'],
    status: 'NOT_IMPLEMENTED',
    targetGate: 2,
    implementedIn: '@sentinel-forge/analyzer',
  },
  {
    id: 'PERF-QUERY-001',
    category: 'PERFORMANCE',
    defaultSeverity: 'MEDIUM',
    title: 'Database query in a loop or unbounded selection',
    description:
      'Detects repeated query execution inside a loop, and SELECT statements without a bound on the returned rows.',
    rationale:
      'Per-iteration queries multiply database round trips and are a frequent cause of tick-time growth as data volume increases.',
    falsePositives: [
      'Batch maintenance code that intentionally runs off the hot path.',
      'Queries against tables known by the author to be small.',
    ],
    evidenceRequirements: ['FILE_REFERENCE with the query line', 'CODE_PATTERN containing the statement'],
    status: 'NOT_IMPLEMENTED',
    targetGate: 2,
    implementedIn: '@sentinel-forge/analyzer',
  },
  {
    id: 'PERF-REGRESSION-001',
    category: 'PERFORMANCE',
    defaultSeverity: 'HIGH',
    title: 'Resource timing regression against baseline',
    description:
      'Detects a statistically meaningful increase in resource tick time compared with a recorded baseline.',
    rationale:
      'A regression identifies which resource changed behaviour, and when, which is the fastest route to a root cause.',
    falsePositives: [
      'Large relative increases on very small absolute values.',
      'Player-count differences between the baseline and the comparison window.',
      'Insufficient sample counts on either side of the comparison.',
    ],
    evidenceRequirements: ['MEASUREMENT with baseline value, current value and sample counts'],
    status: 'NOT_IMPLEMENTED',
    targetGate: 3,
    implementedIn: '@sentinel-forge/performance',
  },
  {
    id: 'SEC-SECRET-001',
    category: 'SECURITY',
    defaultSeverity: 'HIGH',
    title: 'Embedded credential indicator',
    description:
      'Detects credential-shaped strings (tokens, API keys, database passwords, private keys) in resource files.',
    rationale:
      'Credentials committed into resource files are exposed to anyone who obtains the resource, including through leaked archives.',
    falsePositives: [
      'Placeholder values in example configuration.',
      'High-entropy strings that are not credentials (hashes, UUIDs, asset identifiers).',
    ],
    evidenceRequirements: ['FILE_REFERENCE with the line', 'Redacted excerpt — raw secret values are never stored or reported'],
    status: 'NOT_IMPLEMENTED',
    targetGate: 4,
    implementedIn: '@sentinel-forge/security',
  },
  {
    id: 'SEC-WEBHOOK-001',
    category: 'SECURITY',
    defaultSeverity: 'MEDIUM',
    title: 'Embedded webhook endpoint',
    description: 'Detects hard-coded webhook URLs (for example Discord webhooks) in resource files.',
    rationale:
      'A leaked webhook allows a third party to post to the destination channel, and often reveals internal operational structure.',
    falsePositives: ['Documentation or example URLs that are not live endpoints.'],
    evidenceRequirements: ['FILE_REFERENCE with the line', 'Redacted excerpt of the endpoint'],
    status: 'NOT_IMPLEMENTED',
    targetGate: 4,
    implementedIn: '@sentinel-forge/security',
  },
  {
    id: 'SEC-OBFUSCATION-001',
    category: 'SECURITY',
    defaultSeverity: 'MEDIUM',
    title: 'Obfuscation indicators present',
    description:
      'Detects indicators such as dense encoded string literals, decode chains, and string reconstruction patterns.',
    rationale:
      'Obfuscated code cannot be reviewed. It is not evidence of malice, but it does block the normal safeguards a reviewer relies on.',
    falsePositives: [
      'Legitimately minified or bundled JavaScript.',
      'Embedded binary assets encoded as text.',
      'Licence-protection wrappers used by commercial resources.',
    ],
    evidenceRequirements: ['FILE_REFERENCE', 'MEASUREMENT of the indicator density that triggered the finding'],
    status: 'NOT_IMPLEMENTED',
    targetGate: 4,
    implementedIn: '@sentinel-forge/security',
  },
  {
    id: 'SEC-REMOTE-LOAD-001',
    category: 'SECURITY',
    defaultSeverity: 'HIGH',
    title: 'Remote code loading indicator',
    description:
      'Detects a fetch of remote content that is subsequently passed to a code-loading construct.',
    rationale:
      'Code fetched at runtime is not covered by any review of the resource on disk, so what runs cannot be determined from the repository.',
    falsePositives: [
      'Remote fetches used only for data (version checks, configuration payloads).',
      'Update mechanisms that download to disk for manual installation.',
    ],
    evidenceRequirements: ['FILE_REFERENCE for the fetch', 'FILE_REFERENCE for the load construct', 'CODE_PATTERN linking them'],
    status: 'NOT_IMPLEMENTED',
    targetGate: 4,
    implementedIn: '@sentinel-forge/security',
  },
  {
    id: 'SEC-DYNAMIC-EXEC-001',
    category: 'SECURITY',
    defaultSeverity: 'MEDIUM',
    title: 'Dynamic code execution construct',
    description: 'Detects `load`, `loadstring` and equivalent constructs applied to non-literal input.',
    rationale:
      'Dynamically constructed code cannot be analyzed statically, and widens the impact of any input-handling defect.',
    falsePositives: [
      'Sandboxed scripting features intentionally exposed by the resource.',
      'Configuration parsers applied to trusted local files.',
    ],
    evidenceRequirements: ['FILE_REFERENCE with the line', 'CODE_PATTERN containing the construct'],
    status: 'NOT_IMPLEMENTED',
    targetGate: 4,
    implementedIn: '@sentinel-forge/security',
  },
  {
    id: 'SEC-SUSPICIOUS-FILE-001',
    category: 'SECURITY',
    defaultSeverity: 'MEDIUM',
    title: 'Unexpected file type in a resource directory',
    description:
      'Detects executables, archives and other file types that a resource does not normally require.',
    rationale:
      'Unexpected binaries inside a resource are worth a deliberate look before the resource is trusted on a live server.',
    falsePositives: [
      'Resources that legitimately ship native modules or bundled tooling.',
      'Developer working files left inside the resource directory.',
    ],
    evidenceRequirements: ['FILE_REFERENCE', 'FILE_HASH of the unexpected file'],
    status: 'NOT_IMPLEMENTED',
    targetGate: 4,
    implementedIn: '@sentinel-forge/security',
  },
  {
    id: 'INT-CHANGE-001',
    category: 'INTEGRITY',
    defaultSeverity: 'INFO',
    title: 'Resource file changed since the previous snapshot',
    description:
      'Detects added, deleted, modified and hash-changed files between two integrity snapshots.',
    rationale:
      'Knowing exactly what changed, and when, is the anchor for correlating a behaviour change with a code change.',
    falsePositives: [
      'Expected changes from a deliberate resource update.',
      'Files rewritten by the resource itself at runtime (caches, generated configuration).',
    ],
    evidenceRequirements: ['FILE_HASH for both snapshots', 'Snapshot timestamps'],
    status: 'NOT_IMPLEMENTED',
    targetGate: 4,
    implementedIn: '@sentinel-forge/integrity',
  },
]);

const BY_ID: ReadonlyMap<string, RuleCatalogEntry> = new Map(ENTRIES.map((entry) => [entry.id, entry]));

export function listRules(): readonly RuleCatalogEntry[] {
  return ENTRIES;
}

export function getRule(id: string): RuleCatalogEntry | undefined {
  return BY_ID.get(id);
}

export function isKnownRuleId(id: string): boolean {
  return BY_ID.has(id);
}

export function listRulesByCategory(category: RuleCategory): readonly RuleCatalogEntry[] {
  return ENTRIES.filter((entry) => entry.category === category);
}

export function listRulesByStatus(status: RuleStatus): readonly RuleCatalogEntry[] {
  return ENTRIES.filter((entry) => entry.status === status);
}

export function isRuleCategory(value: unknown): value is RuleCategory {
  return typeof value === 'string' && (RULE_CATEGORIES as readonly string[]).includes(value);
}
